function DatosPersonales(){
    return(
        <section className="datos-page">
            <div className="section-content">
                <h2 className="section-title">Tratamiento de datos personales</h2>
                <div className="datos-container">
                    <p>La presente Política de Tratamiento de Datos Personales establece las condiciones bajo las cuales UrbanKicks realiza la recolección, almacenamiento, uso, circulación, administración, transferencia y protección de la información personal suministrada por sus clientes, usuarios, proveedores, colaboradores y visitantes a través de sus plataformas digitales, formularios físicos, redes sociales, campañas publicitarias y demás canales autorizados. UrbanKicks reconoce la importancia de garantizar la privacidad, confidencialidad y seguridad de los datos personales, por lo cual adopta medidas técnicas, humanas y administrativas razonables destinadas a prevenir el acceso no autorizado, pérdida, alteración, divulgación o uso indebido de la información recopilada. Los datos personales podrán ser utilizados para gestionar compras, procesar pagos, coordinar envíos, brindar soporte al cliente, ejecutar campañas promocionales, enviar información comercial, realizar análisis estadísticos, fortalecer la experiencia de navegación, prevenir actividades fraudulentas y cumplir obligaciones legales, fiscales y contractuales. La información suministrada por los usuarios podrá incluir nombres completos, documentos de identificación, números telefónicos, direcciones físicas, correos electrónicos, información de facturación, historial de compras, direcciones IP y demás datos necesarios para la correcta prestación de los servicios ofrecidos por UrbanKicks. El titular de la información autoriza de manera previa, expresa e informada a UrbanKicks para tratar sus datos personales conforme a las finalidades aquí establecidas y acepta que dicha información pueda ser compartida con proveedores tecnológicos, operadores logísticos, plataformas de pago, aliados comerciales y autoridades competentes cuando resulte necesario para el funcionamiento de los servicios o cuando la ley así lo requiera. UrbanKicks se compromete a no vender ni comercializar información personal a terceros no autorizados y a garantizar que cualquier entidad vinculada al tratamiento de datos mantenga obligaciones de confidencialidad y protección de la información. Los titulares de los datos personales tendrán derecho a conocer, actualizar, rectificar, corregir o solicitar la eliminación de su información, así como revocar la autorización otorgada para el tratamiento de sus datos cuando ello sea procedente conforme a la legislación aplicable. Las solicitudes relacionadas con protección de datos podrán realizarse a través de los canales oficiales de atención definidos por la empresa y serán atendidas dentro de los términos establecidos por la normativa vigente. UrbanKicks podrá conservar la información personal durante el tiempo necesario para cumplir las finalidades autorizadas, atender obligaciones legales o resolver posibles controversias derivadas de relaciones comerciales o contractuales.</p>
                </div>
            </div>
        </section>
    )
}
export default DatosPersonales;